name: Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, pi]   # this is why we set the labels
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to target dir
        env:
          PI_TARGET: /home/myk410/Pi-Patreon
        run: |
          mkdir -p "$PI_TARGET"
          rsync -az --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            ./ "$PI_TARGET/"

      - name: Optional: restart app service
        run: |
          sudo systemctl daemon-reload || true
          sudo systemctl restart pi-patreon.service || true
