name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rsync to Raspberry Pi
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ${{ secrets.PI_PATH }}
          remote_host: ${{ secrets.PI_HOST }}
          remote_user: ${{ secrets.PI_USER }}
          remote_key: ${{ secrets.PI_SSH_KEY }}
