name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, pi]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Copy the checked-out code to your live folder
      - name: Sync to /home/myk410/Pi-Patreon
        env:
          PI_TARGET: /home/myk410/Pi-Patreon
        run: |
          mkdir -p "$PI_TARGET"
          rsync -rltDz --delete \
            --no-o --no-g \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "node_modules/" \
            --exclude "__pycache__/" \
            --exclude "*.log" \
            ./ "$PI_TARGET/"

      # (Optional) post-deploy hook (install deps, build, migrate, etc.)
      - name: Post-deploy
        run: |
          cd /home/myk410/Pi-Patreon
          echo "Post-deploy steps go here"
          # python3 -m venv venv && venv/bin/pip install -r requirements.txt
          # npm ci && npm run build

      # (Optional) restart your app's systemd service
      - name: Restart service
        run: |
          sudo systemctl daemon-reload || true
          sudo systemctl restart pi-patreon.service || true
          sudo systemctl --no-pager -l status pi-patreon.service | tail -n 50 || true
